name: WorldStatus
version: '0.0.1'
main: org.worldstatus.WorldStatus
api-version: '1.21'
folia-supported: true
libraries:
  - net.dv8tion:JDA:5.1.2
  - com.squareup.okhttp3:okhttp:4.12.0
  - com.squareup.okio:okio:3.9.0
  - com.fasterxml.jackson.core:jackson-databind:2.17.2
  - com.fasterxml.jackson.core:jackson-core:2.17.2
  - com.fasterxml.jackson.core:jackson-annotations:2.17.2
  - com.neovisionaries:nv-websocket-client:2.14
  - org.apache.commons:commons-collections4:4.4
  - net.sf.trove4j:core:3.1.0
description: Server status plugin with Discord bot integration
authors: [ WorldStatus ]

commands:
  world-status:
    description: Show server world and system status
    usage: /world-status [reload]
    permission: worldstatus.status
    aliases: [ ws, wstatus ]
  worldbar:
    description: Show a progress bar for a metric
    usage: /worldbar <ram|cpu|disk|mspt|tps>
    permission: worldstatus.bar
    aliases: [ wbar ]

permissions:
  worldstatus.*:
    description: All WorldStatus permissions
    default: op
    children:
      worldstatus.status: true
      worldstatus.bar: true
      worldstatus.reload: true

  worldstatus.status:
    description: Use /world-status
    default: op

  worldstatus.bar:
    description: Use /worldbar
    default: op

  worldstatus.reload:
    description: Use /world-status reload
    default: op